### PR TITLE
Create an even more confusing version of Whitespace

### PR DESCRIPTION
**Pull request by troglodytto**

### CODE REVIEW

**Comment by FormerlyChucks** [comment]
I don't really understand what the code does.

**Comment by troglodytto** [comment]
It Prints "jello", But since The Language is Whitespace, It uses whitespaces to do that i.e Spaces, Tabs and Line Feeds

**Comment by troglodytto** [comment]
The previous version had S, L, and T written in it to signify the characters that followed them but they were just comments. The actual code is the whitespace itself.

**Comment by FormerlyChucks** [comment]
Okay, thanks.

**Pull request merged**
