### PR TITLE
Added script to generate one-pager

### PR DESCRIPTION
**Pull request by mducharm**
For easier comparison of different languages, I thought it would be nice to have a markdown one-pager with all the scripts combined together.

Since this repo will change over time & new languages will be added, I thought having a script to consolidate them would be simpler than manually updating this one-pager over time.

### CODE REVIEW

**Comment by FormerlyChucks** [comment]
I get the following traceback when running the script:
```
Traceback (most recent call last):
  File "combine_snippets.py", line 41, in <module>
    main()
  File "combine_snippets.py", line 31, in main
    for d in os.scandir(".")
  File "combine_snippets.py", line 32, in <listcomp>
    if d.name != '.git' and d.is_dir()]
  File "combine_snippets.py", line 21, in create_section
    snippet = create_snippet(f.read())
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

I was thinking about doing something similar, but I planned on doing it with Bash.

**Comment by mducharm** [comment]
Interesting, it looks like the issue is due to the recent addition of Piet (jello.png). The script assumes they're all text files and doesn't account for images; I'll update my PR to check for this. 

(I also considered doing a bash script at first to lose the dependency on python, but don't know bash very well, hence the python script - hope that's okay)

**Comment by FormerlyChucks** [comment]
A Python script is fine since Py is the main lang I use. Bash can get confusing at times.

**Comment by mducharm** [comment]
Sounds good - the last commit should do the trick. I tested it locally as well; if it finds an image, it'll create a link in markdown instead.

**Comment by FormerlyChucks** [comment]
Thank you so much.

Your code runs fast too <3

**Pull request merged**
